// 200x150 light gray png with a border and diagonals, stands in for images
// that are referenced but missing from the project
const PLACEHOLDER_PNG_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAMgAAACWCAIAAAAUvlBOAAADmklEQVR42u3dW07kMBAFUPYvVjKLmzXMB9IIWg04aZftqjr3k4eEbx2g03GSt3eRgLypQAJh/fmUvyLX89/Pt7DYktuqHmE9fI4tuafqCaynX6Q1GSf18cHnsNiSV1T9BIstua3qF1h4yQ1So7DYkhsehmCxJVcljMLCSy5N/xostqganPtlWGxRNfItd2DhhVQgLLaoioLFFlVRsPBCKhAWW1RFwWKLqihYeCEVCIstqqJgsdVcVSAsvNqSWgGLrZ6qVsBiq6GqRbDwakVqNSy2+qhaDYutJqo2wMKrPKmdsNgq3/M2WGzVbngnLLwKt7ofFlsl+zwCFlv1mjwFFl7F2jsLFltlejsOFls1GjsRFl4FWjoXFlup+zkaFlt5mzkdFl5J28gBi610PaSBxVauBjLB6swr3arzwWpoK+N6U8JqZSvpSrPC6sAr9epywypsK/u60sMqaavAiirAqsSrzC9JHVgFplLpT28pWKlnU+wfejVYGYdU8vijJqxE06p6VFsWVoqZFX4frjKsk4dX/sxBfVgHTrHD+agWsI6aZZOznF1gnTDUVpsyesHaON1uW33awdoy44abEzvCWjnsttup+8JaMPXOm/RbwwqdffNLP7rDikDgaiKw5mugCqz5JqgCazIOpMCar4QqsObbogqsybyQAmu+LarAmm+LKrCieCEF1uZ3IsACy18ssLzGAstRIVhy4UUVW2AFvk7HC6yooz+2wIp6T4EtsAJx4AVWlAm2wIrSwBZYrtIBK5UqtlwJ7UposNIO270bqGILrGzTdX8spPACK+Es3YOUKrbASjg893mnii2wPEsHLEOqysvzCv38YDWYiiesGoYVlYblKfZgab/R6rLC6nNCN+lKU8LqtgUl43rzweq5JzPdqjPBcvVLogbSwKIqVw85YFGVro3TYSGVtJmjYVGVt59zYVGVuqUTYSFVoLHjYFFVo7ezYFFVpr1TYCFVrMkjYFFVr8/9sKgq2epOWEgVbngbLKpq97wHFlXlba2GhVQTXkthUdXH1jpYVLWytQIWUg15hcOiqqetWFhUtbUVBQup5rxCYFHF1nxYVLE1GRZSeM2HRRVb82FRxdZkWEjhNR8WVWzNh0UVW5NhIYXXfFhUsTUy92uwqGJrcPqjsJCSSxKGYFElVz38DosquaHiJ1hIyW1e38KiSl6x9RwWVfKirUdYSMkUXl9gUSWzbH2BJTI3YElI/gEqUTZF9bD0AQAAAABJRU5ErkJggg==';

export function placeholderImage(): ArrayBuffer {
  const raw = atob(PLACEHOLDER_PNG_B64);
  const buf = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) buf[i] = raw.charCodeAt(i);
  return buf.buffer;
}
